name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - master  # We don't want branches in doc to trigger builds

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        dir: dist
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
